version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    machine: true
    resource_class: radhigulati/mac1-main
    steps:
      - run: echo "Hi I'm on Self-hosted Runners!"
